# Generated by Django 5.1.4 on 2024-12-11 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProjetoDeLei',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=7, verbose_name='Número')),
                ('descrição', models.CharField(max_length=255, verbose_name='Descrição')),
                ('documento', models.URLField(verbose_name='Link do Documento')),
                ('status', models.CharField(choices=[('Aprovado', 'aproved'), ('Em Análise', 'pending'), ('Negado', 'denied')], max_length=20, verbose_name='Status')),
                ('ano', models.IntegerField(choices=[(2021, '2021'), (2022, '2022'), (2023, '2023'), (2024, '2024')], verbose_name='Ano')),
            ],
            options={
                'verbose_name': 'Projeto de lei',
                'verbose_name_plural': 'Projetos de Lei',
            },
        ),
    ]
