# Generated by Django 5.1.4 on 2024-12-11 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projetodelei',
            old_name='descrição',
            new_name='descricao',
        ),
    ]
